---
# Gitlab fargate runner stack parameters  
app_name: gitlab-ci-fargate-runner
bastion:
  gitlab_runner_version: 14.2.0-1
  VpcId: 
  gitlab_server: gitlab.com
  gitlab_runner_token_secret_name: SMName
  runner_tags: my-tag
  runner_log_output_limit: "4096"
  concurrent_jobs: "10"
  default_ssh_username: root
  docker_image_name: python
  task_definition_cpu: "512"
  task_definition_memory: "1024"
...
