LogLevel = "info"
LogFormat = "text"
LogFile = "fargate.log"

[Fargate]
  Cluster = "${__ECS_CLUSTER__}"
  Region = "${__REGION__}"
  Subnet = "${__SUBNET_ID__}"
  SecurityGroup = "${__SECURITY_GROUP_ID__}"
  TaskDefinition = "${__TASK_DEFINITION__}"

[TaskMetadata]
  Directory = "/opt/gitlab-runner/metadata"

[SSH]
  Username = "${__SSH_USERNAME__}"
  Port = 22